[package]
name = "command"
version = "0.1.0"
edition = "2021"

[package.metadata.component]
package = "docs:calculator"
target = { path = "../calculator.wit", world = "app" }

[package.metadata.component.dependencies]

[dependencies]
bitflags = "2.4.2"
wit-bindgen-rt = "0.22.0"
